### ISSUE TITLE
libdlap not being included in Docker image

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/guacamole-user-sync#17]
The guacamole-user-sync image is missing libldap.

```
guacamole-user-sync  | Traceback (most recent call last):
guacamole-user-sync  |   File "/app/synchronise.py", line 6, in <module>
guacamole-user-sync  |     from guacamole_user_sync.ldap import LDAPClient
guacamole-user-sync  |   File "/usr/local/lib/python3.11/dist-packages/guacamole_user_sync/ldap/__init__.py", line 1, in <module>
guacamole-user-sync  |     from .ldap_client import LDAPClient
guacamole-user-sync  |   File "/usr/local/lib/python3.11/dist-packages/guacamole_user_sync/ldap/ldap_client.py", line 3, in <module>
guacamole-user-sync  |     import ldap
guacamole-user-sync  |   File "/usr/local/lib/python3.11/dist-packages/ldap/__init__.py", line 34, in <module>
guacamole            |   inflating: /home/guacamole/.guacamole/logback.xml
guacamole-user-sync  |     import _ldap
guacamole-user-sync  | ImportError: libldap-2.5.so.0: cannot open shared object file: No such file or directory
```

This library should be built into the `python-ldap` wheel by `auditwheel` during the Dockerfile build process.

**Comment by JimMadge** [comment]
The Dockerfile looks complicated.

Is it not possible to do something like,

- Install system dependencies (psql, libldap _etc._)
- Copy src and pyrpoject.toml
- `pip install .`

**Comment by jemrobinson** [comment]
There is no package manager in the distroless image.

**Comment by JimMadge** [comment]
Do we need a distroless image?

**Comment by jemrobinson** [comment]
It reduces the image size from ~500 MB to ~100MB. It reduces the number of known vulnerabilities from ~100 to <5.

**Comment by JimMadge** [comment]
Is that a deal breaker? Feels like it is going to make building the image quite difficult.

**Comment by jemrobinson** [comment]
It's honestly not that bad. We build all our dependencies into wheels. `auditwheel` finds shared libraries that are needed by each wheel and adds them to it. Then the final image can just install the wheels. For some reason it's missing that `ldap` depends on `libldap` but I assume there's a way to prompt it.

**Comment by JimMadge** [comment]
Possibly this limitation,

> auditwheel uses the [DT_NEEDED](https://en.wikipedia.org/wiki/Direct_binding) information (like ldd) from the Python extension modules to determine which system libraries they depend on. Code that dynamically loads libraries at runtime using ctypes / cffi (from Python) or dlopen (from C/C++) doesn’t contain this information in a way that can be statically determined, so dependencies that are loaded via those mechanisms will be missed.

**Comment by JimMadge** [comment]
Building the container image, I can't see any output from auditwheel.

**Comment by JimMadge** [comment]
```console
root@a7a9287a7829:/dist# auditwheel repair guacamole_user_sync-0.6.0-py3-none-any.whl --plat manylinux_2_34_aarch64
INFO:auditwheel.main_repair:Repairing guacamole_user_sync-0.6.0-py3-none-any.whl
INFO:auditwheel.main_repair:This does not look like a platform wheel, no ELF executable or shared library file (including compiled Python C extension) found in the wheel archive
```

Although, that wheel was built with `hatch build` so not exactly the same.

**Comment by JimMadge** [comment]
I'm also asking, if I make a PR that changes to a debian/alpine container would that be rejected?

**Comment by jemrobinson** [comment]
I think I've got a fix for this. Should be able to confirm today.
